# Generated by Django 5.0.4 on 2024-05-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(choices=[('1', '1'), ('2', '2'), ('first', 'iron'), ('second', 'zinc')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
